### PR TITLE
Fix the noise test

### PR DESCRIPTION
**Pull request by planes**
Numpy now defaulted the results of ceil to being an array a rather than a scalar. It is now an scalar int.

### CODE REVIEW

**Comment by planes** [comment]
So the noise test is now working. However the changes for the Concorde are not included in this pull request.

**Comment by planes** [comment]
I think we should pull the concorde fixes at the same time as well. If not in the same branch, at the same time. Reason being is that travis will fail and send an email as soon as this is merged.

**Comment by timdmacdo** [comment]
Okay. I'm waiting on the aero folders pull to make the request since it depends on those files.

**Comment by planes** [comment]
Travis is fixed. Merging.

**Pull request merged**
