### PR TITLE
Constant_Throttle_Constant_Rate for glide descent

### PR DESCRIPTION
**Pull request by KillingVector**
Tested using Solar UAV and some tailless bwb triangle (marginally stable).
Solar UAV test - set engine number to zero
Purpose: for use to optimise L/D, minimise descent rate, maximise downrange

Future dev (next step): rewrite this/create additional script that functions with no throttle input and no unknown_throttle

Included: analysis and method, __init__.py files assoc with both.  No identified conflicts.
Advice and changes encouraged (:

Notes:  method - init file, I've apparently deleted and added identical lines for a net zero change on one addition. Magic.
Minor error handling for non-descent descent rates (if user enters a climb value, at the moment throws Attribute error and tells the user to not use negative value as z is down), (if user enters 0, throws error informing user that this is an invalid value for descent mission).

--Ash

### CODE REVIEW

**Comment by KillingVector** [comment]
@coveralls Hello, could you please let me know a little more information so that I may fix up this file.  Unfortunately, I don't understand fully what coverage is.  Does my file clash with one of the files in your branch?  Can you tell me if this traces to a specific file?
Thank you for the feedback!

**Comment by WalterMaier** [comment]
@KillingVector coveralls is an automated script that checks how many lines in SUAVE are actually being used. In this case it looks like the "did not converge" portion was not used (That's a good thing).   The SAUVE team is looking at your pull request and will make changes/leave comment soon.  Thanks for your help!

**Comment by JTrentSmart** [comment]
Made some changes to the comments, formatting and documentation. Will review coverage issue before approval.

**Comment by KillingVector** [comment]
Okay!  Thank you for the feedback, I'm still getting the hang of this, so I will work through this process and get back to you all when I've got that working.  I may swing by the forums if I have any questions about getting the implementation of the check, if I need.

I appreciate all your patience!

**Comment by WalterMaier** [comment]
no  updates....will wait until changes are made

**Pull request closed without merging**
