### PR TITLE
AVL/OpenVSP Matching

### PR DESCRIPTION
**Pull request by timdmacdo**
This modifies the AVL and OpenVSP scripts so that output matches for the cases where no wing segments and defined and all segments are defined. It also has a few bug fixes.

### CODE REVIEW

**Comment by timdmacdo** [comment]
I found another bug in how twist is assigned, will fix today.

**Comment by timdmacdo** [comment]
I've finished the fixes

**Comment by planes** [comment]
Looks good to me. It's annoying that coveralls says it's unsuccessful even if reduces coverage by 0.06 percent...

**Comment by planes** [comment]
I'll yank this in now.

**Comment by mclarke2** [comment]
I reviewed the geometry changes in the two scripts. They look fine to me

**Pull request merged**
