### PR TITLE
Constant Calibrated Airspeed climb segment

### PR DESCRIPTION
**Pull request by stankarpuktubs**
# Pull Request Checklist
 * Merge in the latest Develop branch changes to your branch
 * Remove .pyc files from your repository:
   * Linux/Mac
     * find . -name *.pyc -delete
   * Windows
     * del /S *.pyc
 * Run automatic regression and makes sure everything is passing
 * Did you make a new regression test that covers your new code?
 * Did you update your docstrings?
 * Did you update your headers to include your name and date?
 * Do a final compare with the Develop branch to be sure what you're changing

### CODE REVIEW

**Review by planes — COMMENTED** [review]
Hey this code looks great!

[Can you just add a segment into the segment test too?](https://github.com/suavecode/SUAVE/blob/develop/regression/scripts/segments/segment_test.py)

**Comment by planes** [comment]
Hey, looks like coveralls will not allow this to be merged until there is a regression added for these files.

**Review by planes — APPROVED** [review]

**Comment by planes** [comment]
Approved. If you're happy with it, you can hit the merge button.

**Comment by stankarpuktubs** [comment]
I guess I have no write access to merge the request ("Only those with write access to this repository can merge pull requests."). Is there anything I am doing wrong?

**Comment by planes** [comment]
> I guess I have no write access to merge the request ("Only those with write access to this repository can merge pull requests."). Is there anything I am doing wrong?

I apologize, I didn't realize you didn't have the ability to merge.

**Comment by planes** [comment]
Thanks for your contribution. Nice work!

**Comment by stankarpuktubs** [comment]
Thank you!
I am going to pull requests one-by-one, so there we resolve anything at a more-less steady pace. Preparing the next one.

**Pull request merged**
